// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUfbkHLtIhUL0hUIW8R7YF35OmWyoeDdg',
    appId: '1:1062760804609:web:ebdd5a8eae31a0b92e6b00',
    messagingSenderId: '1062760804609',
    projectId: 'minimal-melo-app',
    authDomain: 'minimal-melo-app.firebaseapp.com',
    storageBucket: 'minimal-melo-app.firebasestorage.app',
    measurementId: 'G-TZDBGD1RRJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOpOuUxbSigP2CxxFlGi70TJHxLFKSlOg',
    appId: '1:1062760804609:android:a941def0106569282e6b00',
    messagingSenderId: '1062760804609',
    projectId: 'minimal-melo-app',
    storageBucket: 'minimal-melo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6bjXa-eGQvSZuSxiesnbSabmoRi07iRU',
    appId: '1:1062760804609:ios:117fe02c7625380f2e6b00',
    messagingSenderId: '1062760804609',
    projectId: 'minimal-melo-app',
    storageBucket: 'minimal-melo-app.firebasestorage.app',
    iosBundleId: 'com.example.melo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6bjXa-eGQvSZuSxiesnbSabmoRi07iRU',
    appId: '1:1062760804609:ios:117fe02c7625380f2e6b00',
    messagingSenderId: '1062760804609',
    projectId: 'minimal-melo-app',
    storageBucket: 'minimal-melo-app.firebasestorage.app',
    iosBundleId: 'com.example.melo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUfbkHLtIhUL0hUIW8R7YF35OmWyoeDdg',
    appId: '1:1062760804609:web:d813675ba59251c52e6b00',
    messagingSenderId: '1062760804609',
    projectId: 'minimal-melo-app',
    authDomain: 'minimal-melo-app.firebaseapp.com',
    storageBucket: 'minimal-melo-app.firebasestorage.app',
    measurementId: 'G-SXZHN41WMH',
  );
}
